# Generated by Django 4.1.5 on 2023-03-28 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_chart', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referral_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('withdraw', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fund', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
