# Generated by Django 4.1.7 on 2023-03-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
