# Generated by Django 4.1.7 on 2023-04-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='deposit_datetime',
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
